#!/bin/bash

main() {
  source wsl-vhd >/dev/null 2>&1
  # test logging::
  logging::debug "test debug"
  logging::info "test info"
  logging::warning "test warning"
  logging::error "test error"
  logging::critical "test critical"

  # test path::
  paths=(
    '/mnt/c/disk.vhdx'
    './mnt/c/disk.vhdx'
    'mnt/c/disk.vhdx'
    'C:\disk.vhdx'
    'c:\disk.vhdx'
    '\\?\C:\foo.vhdx'
    '\\?\foo.vhdx'
    'foo.vhdx'
    '.\.android\foo.vhdx'
    '~/foo.vhd'
  )

  printf '====================================\n'
  printf 'Test path::to_unix\n'
  printf '====================================\n'
  for path in "${paths[@]}"; do
    printf '[%s] -> [%s]\n' "$path" "$(path::to_unix "$path")"
  done

  printf '====================================\n'
  printf 'Test path::to_win\n'
  printf '====================================\n'
  for path in "${paths[@]}"; do
    printf '[%s] -> [%s]\n' "$path" "$(path::to_win "$path")"
  done

  printf '====================================\n'
  printf 'Test vhd::mountpoint\n'
  printf '====================================\n'
  for path in "${paths[@]}"; do
    printf '[%s] -> [%s]\n' "$path" "$(vhd::mountpoint "$path")"
  done
}

main "$@"
